CREATE TRIGGER INSERT_LIKE_TRACK_UPDATE_TRACK
    AFTER INSERT
    ON LIKE_TRACK
    FOR EACH ROW CALL "com.BayWave.Triggers.InsertLikeTrackUpdateTrackTrigger";
CREATE TRIGGER DELETE_LIKE_TRACK_UPDATE_TRACK
    AFTER DELETE
    ON LIKE_TRACK
    FOR EACH ROW CALL "com.BayWave.Triggers.DeleteLikeTrackUpdateTrackTrigger";

CREATE TRIGGER INSERT_LIKE_ALBUM_UPDATE_ALBUM
    AFTER INSERT
    ON LIKE_ALBUM
    FOR EACH ROW CALL "com.BayWave.Triggers.InsertLikeAlbumUpdateAlbumTrigger";
CREATE TRIGGER DELETE_LIKE_ALBUM_UPDATE_ALBUM
    AFTER DELETE
    ON LIKE_ALBUM
    FOR EACH ROW CALL "com.BayWave.Triggers.DeleteLikeAlbumUpdateAlbumTrigger";

COMMIT;